apiVersion: v1
kind: Pod
metadata:
  name: javaweb-2

spec:
  containers:
  - image: nginx
    name: war
    lifecycle:
      postStart:
        exec:
          command:
            - "cp"
            - "/sample.war"
            - "/app"


      preStop:
        httpGet:
          host: 192.168.1.1
          path: /notify
          port: 8080

  