apiVersion: v1
kind: Pod
metadata:
  name: my-app

spec:
  restartPolicy: OnFailure
  containers:
  - name: app
    image: nginx
    lifecycle:
      preStop:
        httpGet:
          host: 192.168.1.1
          path: /notify
          port: 8080
