apiVersion: v1
kind: Pod
metadata:
  name: my-app

spec:
  restartPolicy: OnFailure
  containers:
  - name: app
    image: nginx
    ports:
    - name: web
      containerPort: 80
      protocol: TCP
  hostNetwork: true