apiVersion: v1
kind: Pod
metadata:
  name: my-nginx

spec:
  restartPolicy: OnFailure
  containers:
  - name: nginx
    image: nginx
    ports:
    - name: web
      containerPort: 80
      protocol: TCP
      hostIP: 0.0.0.0
      hostPort: 80