apiVersion: v1
kind: Pod
metadata:
  name: liveness-exec-pod
  labels:
    test: liveness

spec:
  containers:
  - name: liveness
    image: "ubuntu:14.04"
    command:
    - /bin/sh
    - -c
    - echo ok > /tmp/health; sleep 60; rm -rf /tmp/health; sleep 600
    livenessProbe:
      exec:
        command:
          - cat
          - /tmp/health
      initialDelaySeconds: 15
      timeoutSeconds: 1


