# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'weibo_proxy.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(542, 325)
        self.proxy_status = QtWidgets.QLabel(Dialog)
        self.proxy_status.setGeometry(QtCore.QRect(220, 30, 161, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.proxy_status.setFont(font)
        self.proxy_status.setText("")
        self.proxy_status.setObjectName("proxy_status")
        self.code_account_label = QtWidgets.QLabel(Dialog)
        self.code_account_label.setGeometry(QtCore.QRect(40, 160, 60, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.code_account_label.setFont(font)
        self.code_account_label.setObjectName("code_account_label")
        self.code_password_label = QtWidgets.QLabel(Dialog)
        self.code_password_label.setGeometry(QtCore.QRect(40, 210, 60, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.code_password_label.setFont(font)
        self.code_password_label.setObjectName("code_password_label")
        self.code_status = QtWidgets.QLabel(Dialog)
        self.code_status.setGeometry(QtCore.QRect(220, 30, 381, 31))
        self.code_status.setText("")
        self.code_status.setObjectName("code_status")
        self.proxy_text = QtWidgets.QLineEdit(Dialog)
        self.proxy_text.setGeometry(QtCore.QRect(360, 180, 141, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.proxy_text.setFont(font)
        self.proxy_text.setObjectName("proxy_text")
        self.code_account = QtWidgets.QLineEdit(Dialog)
        self.code_account.setGeometry(QtCore.QRect(90, 160, 141, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.code_account.setFont(font)
        self.code_account.setStyleSheet("")
        self.code_account.setObjectName("code_account")
        self.code_password = QtWidgets.QLineEdit(Dialog)
        self.code_password.setGeometry(QtCore.QRect(90, 210, 141, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.code_password.setFont(font)
        self.code_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.code_password.setObjectName("code_password")
        self.main_win = QtWidgets.QPushButton(Dialog)
        self.main_win.setGeometry(QtCore.QRect(40, 20, 111, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.main_win.setFont(font)
        self.main_win.setStyleSheet("border-image:url(ico/mainBt.png)")
        self.main_win.setText("")
        self.main_win.setObjectName("main_win")
        self.code_bt = QtWidgets.QPushButton(Dialog)
        self.code_bt.setGeometry(QtCore.QRect(40, 260, 80, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.code_bt.setFont(font)
        self.code_bt.setStyleSheet("border-image:url(ico/validate.png)")
        self.code_bt.setText("")
        self.code_bt.setObjectName("code_bt")
        self.code_clean = QtWidgets.QPushButton(Dialog)
        self.code_clean.setGeometry(QtCore.QRect(150, 260, 80, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.code_clean.setFont(font)
        self.code_clean.setStyleSheet("border-image:url(ico/eliminate.png)")
        self.code_clean.setText("")
        self.code_clean.setObjectName("code_clean")
        self.proxy_bt = QtWidgets.QPushButton(Dialog)
        self.proxy_bt.setGeometry(QtCore.QRect(310, 260, 80, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.proxy_bt.setFont(font)
        self.proxy_bt.setStyleSheet("border-image:url(ico/validate.png)")
        self.proxy_bt.setText("")
        self.proxy_bt.setObjectName("proxy_bt")
        self.proxy_clean = QtWidgets.QPushButton(Dialog)
        self.proxy_clean.setGeometry(QtCore.QRect(420, 260, 80, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.proxy_clean.setFont(font)
        self.proxy_clean.setStyleSheet("border-image:url(ico/eliminate.png)")
        self.proxy_clean.setText("")
        self.proxy_clean.setObjectName("proxy_clean")
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(0, 60, 601, 21))
        self.line_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_3.setLineWidth(1)
        self.line_3.setMidLineWidth(1)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(260, 70, 20, 271))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.buy_code = QtWidgets.QPushButton(Dialog)
        self.buy_code.setGeometry(QtCore.QRect(40, 90, 190, 40))
        self.buy_code.setStyleSheet("border-image:url(ico/code.png)")
        self.buy_code.setText("")
        self.buy_code.setObjectName("buy_code")
        self.buy_proxy = QtWidgets.QPushButton(Dialog)
        self.buy_proxy.setGeometry(QtCore.QRect(310, 90, 190, 40))
        self.buy_proxy.setStyleSheet("border-image:url(ico/proxy.png)")
        self.buy_proxy.setText("")
        self.buy_proxy.setObjectName("buy_proxy")
        self.code_account_label_2 = QtWidgets.QLabel(Dialog)
        self.code_account_label_2.setGeometry(QtCore.QRect(310, 180, 60, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.code_account_label_2.setFont(font)
        self.code_account_label_2.setObjectName("code_account_label_2")
        self.line_2.raise_()
        self.proxy_status.raise_()
        self.code_account_label.raise_()
        self.code_password_label.raise_()
        self.code_status.raise_()
        self.proxy_text.raise_()
        self.code_account.raise_()
        self.code_password.raise_()
        self.main_win.raise_()
        self.code_bt.raise_()
        self.code_clean.raise_()
        self.proxy_bt.raise_()
        self.proxy_clean.raise_()
        self.line_3.raise_()
        self.buy_code.raise_()
        self.buy_proxy.raise_()
        self.code_account_label_2.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "微博爬虫软件"))
        self.code_account_label.setText(_translate("Dialog", "账号"))
        self.code_password_label.setText(_translate("Dialog", "密码"))
        self.code_account_label_2.setText(_translate("Dialog", "单号"))

