# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'weibo_release.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1030, 619)
        self.main_win = QtWidgets.QPushButton(Dialog)
        self.main_win.setGeometry(QtCore.QRect(40, 20, 111, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.main_win.setFont(font)
        self.main_win.setStyleSheet("border-image:url(ico/mainBt.png)")
        self.main_win.setText("")
        self.main_win.setObjectName("main_win")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(40, 100, 60, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.user_check_proxy = QtWidgets.QPushButton(Dialog)
        self.user_check_proxy.setGeometry(QtCore.QRect(120, 100, 100, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.user_check_proxy.setFont(font)
        self.user_check_proxy.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.user_check_proxy.setObjectName("user_check_proxy")
        self.importcsv = QtWidgets.QPushButton(Dialog)
        self.importcsv.setGeometry(QtCore.QRect(120, 150, 100, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.importcsv.sizePolicy().hasHeightForWidth())
        self.importcsv.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.importcsv.setFont(font)
        self.importcsv.setObjectName("importcsv")
        self.exportcsv = QtWidgets.QPushButton(Dialog)
        self.exportcsv.setGeometry(QtCore.QRect(240, 150, 100, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exportcsv.sizePolicy().hasHeightForWidth())
        self.exportcsv.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.exportcsv.setFont(font)
        self.exportcsv.setObjectName("exportcsv")
        self.release_pic = QtWidgets.QPushButton(Dialog)
        self.release_pic.setGeometry(QtCore.QRect(120, 200, 100, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.release_pic.setFont(font)
        self.release_pic.setAutoFillBackground(False)
        self.release_pic.setObjectName("release_pic")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 150, 60, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 200, 60, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(40, 250, 60, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(40, 300, 60, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.hour = QtWidgets.QComboBox(Dialog)
        self.hour.setGeometry(QtCore.QRect(240, 300, 80, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hour.sizePolicy().hasHeightForWidth())
        self.hour.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.hour.setFont(font)
        self.hour.setObjectName("hour")
        self.hour.addItem("")
        self.hour.addItem("")
        self.hour.addItem("")
        self.hour.addItem("")
        self.hour.addItem("")
        self.hour.addItem("")
        self.hour.addItem("")
        self.hour.addItem("")
        self.hour.addItem("")
        self.hour.addItem("")
        self.hour.addItem("")
        self.hour.addItem("")
        self.hour.addItem("")
        self.hour.addItem("")
        self.hour.addItem("")
        self.hour.addItem("")
        self.hour.addItem("")
        self.hour.addItem("")
        self.hour.addItem("")
        self.hour.addItem("")
        self.hour.addItem("")
        self.hour.addItem("")
        self.hour.addItem("")
        self.hour.addItem("")
        self.minute = QtWidgets.QComboBox(Dialog)
        self.minute.setGeometry(QtCore.QRect(360, 300, 80, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.minute.sizePolicy().hasHeightForWidth())
        self.minute.setSizePolicy(sizePolicy)
        self.minute.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.minute.setFont(font)
        self.minute.setObjectName("minute")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.minute.addItem("")
        self.label_8 = QtWidgets.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(330, 300, 21, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(450, 300, 21, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.release_bt = QtWidgets.QPushButton(Dialog)
        self.release_bt.setGeometry(QtCore.QRect(190, 370, 111, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.release_bt.setFont(font)
        self.release_bt.setStyleSheet("border-image:url(ico/bt.png)")
        self.release_bt.setObjectName("release_bt")
        self.release_delay = QtWidgets.QComboBox(Dialog)
        self.release_delay.setGeometry(QtCore.QRect(120, 250, 100, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.release_delay.sizePolicy().hasHeightForWidth())
        self.release_delay.setSizePolicy(sizePolicy)
        self.release_delay.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.release_delay.setFont(font)
        self.release_delay.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.release_delay.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContentsOnFirstShow)
        self.release_delay.setObjectName("release_delay")
        self.release_delay.addItem("")
        self.release_delay.addItem("")
        self.release_delay.addItem("")
        self.release_delay.addItem("")
        self.dateEdit = QtWidgets.QDateEdit(Dialog)
        self.dateEdit.setGeometry(QtCore.QRect(120, 300, 100, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dateEdit.sizePolicy().hasHeightForWidth())
        self.dateEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.dateEdit.setFont(font)
        self.dateEdit.setCalendarPopup(True)
        self.dateEdit.setObjectName("dateEdit")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(80, 470, 351, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.state_value = QtWidgets.QPlainTextEdit(Dialog)
        self.state_value.setGeometry(QtCore.QRect(40, 530, 381, 71))
        self.state_value.setObjectName("state_value")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(0, 430, 481, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(470, 70, 20, 551))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(0, 60, 1301, 21))
        self.line_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_3.setLineWidth(1)
        self.line_3.setMidLineWidth(1)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(40, 470, 31, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_9.setFont(font)
        self.label_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_9.setTextFormat(QtCore.Qt.AutoText)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(40, 510, 381, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background:rgb(198, 198, 198)")
        self.label_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_10.setTextFormat(QtCore.Qt.AutoText)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(500, 90, 511, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background:rgb(198, 198, 198)")
        self.label_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_11.setTextFormat(QtCore.Qt.AutoText)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.release_table = QtWidgets.QTableWidget(Dialog)
        self.release_table.setGeometry(QtCore.QRect(500, 120, 511, 481))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.release_table.setFont(font)
        self.release_table.setRowCount(1)
        self.release_table.setColumnCount(5)
        self.release_table.setObjectName("release_table")
        self.release_table.horizontalHeader().setVisible(True)
        self.release_table.horizontalHeader().setCascadingSectionResizes(False)
        self.release_table.horizontalHeader().setSortIndicatorShown(False)
        self.release_table.horizontalHeader().setStretchLastSection(False)
        self.release_table.verticalHeader().setCascadingSectionResizes(False)
        self.release_table.verticalHeader().setHighlightSections(True)
        self.release_table.verticalHeader().setSortIndicatorShown(False)
        self.release_table.verticalHeader().setStretchLastSection(False)

        self.retranslateUi(Dialog)
        self.release_delay.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "微博爬虫软件"))
        self.label_4.setText(_translate("Dialog", "服务验证"))
        self.user_check_proxy.setText(_translate("Dialog", "验证代理IP"))
        self.importcsv.setText(_translate("Dialog", "导入CSV"))
        self.exportcsv.setText(_translate("Dialog", "导出CSV"))
        self.release_pic.setText(_translate("Dialog", "选择图片"))
        self.label_3.setText(_translate("Dialog", "文件通道"))
        self.label_2.setText(_translate("Dialog", "内容编辑"))
        self.label_5.setText(_translate("Dialog", "发布间隔"))
        self.label_6.setText(_translate("Dialog", "定时发布"))
        self.hour.setItemText(0, _translate("Dialog", "00"))
        self.hour.setItemText(1, _translate("Dialog", "01"))
        self.hour.setItemText(2, _translate("Dialog", "02"))
        self.hour.setItemText(3, _translate("Dialog", "03"))
        self.hour.setItemText(4, _translate("Dialog", "04"))
        self.hour.setItemText(5, _translate("Dialog", "05"))
        self.hour.setItemText(6, _translate("Dialog", "06"))
        self.hour.setItemText(7, _translate("Dialog", "07"))
        self.hour.setItemText(8, _translate("Dialog", "08"))
        self.hour.setItemText(9, _translate("Dialog", "09"))
        self.hour.setItemText(10, _translate("Dialog", "10"))
        self.hour.setItemText(11, _translate("Dialog", "11"))
        self.hour.setItemText(12, _translate("Dialog", "12"))
        self.hour.setItemText(13, _translate("Dialog", "13"))
        self.hour.setItemText(14, _translate("Dialog", "14"))
        self.hour.setItemText(15, _translate("Dialog", "15"))
        self.hour.setItemText(16, _translate("Dialog", "16"))
        self.hour.setItemText(17, _translate("Dialog", "17"))
        self.hour.setItemText(18, _translate("Dialog", "18"))
        self.hour.setItemText(19, _translate("Dialog", "19"))
        self.hour.setItemText(20, _translate("Dialog", "20"))
        self.hour.setItemText(21, _translate("Dialog", "21"))
        self.hour.setItemText(22, _translate("Dialog", "22"))
        self.hour.setItemText(23, _translate("Dialog", "23"))
        self.minute.setItemText(0, _translate("Dialog", "00"))
        self.minute.setItemText(1, _translate("Dialog", "01"))
        self.minute.setItemText(2, _translate("Dialog", "02"))
        self.minute.setItemText(3, _translate("Dialog", "03"))
        self.minute.setItemText(4, _translate("Dialog", "04"))
        self.minute.setItemText(5, _translate("Dialog", "05"))
        self.minute.setItemText(6, _translate("Dialog", "06"))
        self.minute.setItemText(7, _translate("Dialog", "07"))
        self.minute.setItemText(8, _translate("Dialog", "08"))
        self.minute.setItemText(9, _translate("Dialog", "09"))
        self.minute.setItemText(10, _translate("Dialog", "10"))
        self.minute.setItemText(11, _translate("Dialog", "11"))
        self.minute.setItemText(12, _translate("Dialog", "12"))
        self.minute.setItemText(13, _translate("Dialog", "13"))
        self.minute.setItemText(14, _translate("Dialog", "14"))
        self.minute.setItemText(15, _translate("Dialog", "15"))
        self.minute.setItemText(16, _translate("Dialog", "16"))
        self.minute.setItemText(17, _translate("Dialog", "17"))
        self.minute.setItemText(18, _translate("Dialog", "18"))
        self.minute.setItemText(19, _translate("Dialog", "19"))
        self.minute.setItemText(20, _translate("Dialog", "20"))
        self.minute.setItemText(21, _translate("Dialog", "21"))
        self.minute.setItemText(22, _translate("Dialog", "22"))
        self.minute.setItemText(23, _translate("Dialog", "23"))
        self.minute.setItemText(24, _translate("Dialog", "24"))
        self.minute.setItemText(25, _translate("Dialog", "25"))
        self.minute.setItemText(26, _translate("Dialog", "26"))
        self.minute.setItemText(27, _translate("Dialog", "27"))
        self.minute.setItemText(28, _translate("Dialog", "28"))
        self.minute.setItemText(29, _translate("Dialog", "29"))
        self.minute.setItemText(30, _translate("Dialog", "30"))
        self.minute.setItemText(31, _translate("Dialog", "31"))
        self.minute.setItemText(32, _translate("Dialog", "32"))
        self.minute.setItemText(33, _translate("Dialog", "33"))
        self.minute.setItemText(34, _translate("Dialog", "34"))
        self.minute.setItemText(35, _translate("Dialog", "35"))
        self.minute.setItemText(36, _translate("Dialog", "36"))
        self.minute.setItemText(37, _translate("Dialog", "37"))
        self.minute.setItemText(38, _translate("Dialog", "38"))
        self.minute.setItemText(39, _translate("Dialog", "39"))
        self.minute.setItemText(40, _translate("Dialog", "40"))
        self.minute.setItemText(41, _translate("Dialog", "41"))
        self.minute.setItemText(42, _translate("Dialog", "42"))
        self.minute.setItemText(43, _translate("Dialog", "43"))
        self.minute.setItemText(44, _translate("Dialog", "44"))
        self.minute.setItemText(45, _translate("Dialog", "45"))
        self.minute.setItemText(46, _translate("Dialog", "46"))
        self.minute.setItemText(47, _translate("Dialog", "47"))
        self.minute.setItemText(48, _translate("Dialog", "48"))
        self.minute.setItemText(49, _translate("Dialog", "49"))
        self.minute.setItemText(50, _translate("Dialog", "50"))
        self.minute.setItemText(51, _translate("Dialog", "51"))
        self.minute.setItemText(52, _translate("Dialog", "52"))
        self.minute.setItemText(53, _translate("Dialog", "53"))
        self.minute.setItemText(54, _translate("Dialog", "54"))
        self.minute.setItemText(55, _translate("Dialog", "55"))
        self.minute.setItemText(56, _translate("Dialog", "56"))
        self.minute.setItemText(57, _translate("Dialog", "57"))
        self.minute.setItemText(58, _translate("Dialog", "58"))
        self.minute.setItemText(59, _translate("Dialog", "59"))
        self.label_8.setText(_translate("Dialog", "时"))
        self.label_7.setText(_translate("Dialog", "分"))
        self.release_bt.setText(_translate("Dialog", "发布"))
        self.release_delay.setItemText(0, _translate("Dialog", "不延时"))
        self.release_delay.setItemText(1, _translate("Dialog", "延时5秒"))
        self.release_delay.setItemText(2, _translate("Dialog", "延时10秒"))
        self.release_delay.setItemText(3, _translate("Dialog", "延时15秒"))
        self.dateEdit.setDisplayFormat(_translate("Dialog", "yyyy-M-d"))
        self.label_9.setText(_translate("Dialog", "进度"))
        self.label_10.setText(_translate("Dialog", "状态"))
        self.label_11.setText(_translate("Dialog", "发布内容"))

