# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'weibo_collect.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(975, 546)
        self.collect_state = QtWidgets.QPlainTextEdit(Dialog)
        self.collect_state.setGeometry(QtCore.QRect(40, 460, 381, 71))
        self.collect_state.setObjectName("collect_state")
        self.collect_data = QtWidgets.QTableWidget(Dialog)
        self.collect_data.setGeometry(QtCore.QRect(460, 120, 501, 411))
        self.collect_data.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.collect_data.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.collect_data.setColumnCount(5)
        self.collect_data.setObjectName("collect_data")
        self.collect_data.setRowCount(0)
        self.collect_data.horizontalHeader().setMinimumSectionSize(19)
        self.collect_start = QtWidgets.QPushButton(Dialog)
        self.collect_start.setGeometry(QtCore.QRect(190, 320, 111, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.collect_start.setFont(font)
        self.collect_start.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.collect_start.setStyleSheet("border-image:url(ico/bt.png)")
        self.collect_start.setObjectName("collect_start")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(80, 400, 351, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(40, 400, 31, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_9.setFont(font)
        self.label_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_9.setTextFormat(QtCore.Qt.AutoText)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(40, 440, 381, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("background:rgb(198, 198, 198)")
        self.label_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_10.setTextFormat(QtCore.Qt.AutoText)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Dialog)
        self.label_11.setGeometry(QtCore.QRect(460, 90, 501, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("background:rgb(198, 198, 198)")
        self.label_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.label_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_11.setTextFormat(QtCore.Qt.AutoText)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.line_2 = QtWidgets.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(430, 70, 20, 551))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(0, 370, 441, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.main_win = QtWidgets.QPushButton(Dialog)
        self.main_win.setGeometry(QtCore.QRect(40, 20, 110, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.main_win.setFont(font)
        self.main_win.setStyleSheet("border-image:url(ico/mainBt.png)")
        self.main_win.setText("")
        self.main_win.setObjectName("main_win")
        self.collect_user = QtWidgets.QLineEdit(Dialog)
        self.collect_user.setGeometry(QtCore.QRect(120, 100, 110, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.collect_user.setFont(font)
        self.collect_user.setObjectName("collect_user")
        self.collect_password = QtWidgets.QLineEdit(Dialog)
        self.collect_password.setGeometry(QtCore.QRect(310, 100, 110, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.collect_password.setFont(font)
        self.collect_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.collect_password.setObjectName("collect_password")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(250, 100, 51, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 100, 51, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(40, 150, 51, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.collect_keyword = QtWidgets.QLineEdit(Dialog)
        self.collect_keyword.setGeometry(QtCore.QRect(120, 150, 221, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.collect_keyword.setFont(font)
        self.collect_keyword.setObjectName("collect_keyword")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(40, 210, 51, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.select_pic = QtWidgets.QCheckBox(Dialog)
        self.select_pic.setGeometry(QtCore.QRect(120, 210, 60, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.select_pic.setFont(font)
        self.select_pic.setObjectName("select_pic")
        self.select_video = QtWidgets.QCheckBox(Dialog)
        self.select_video.setGeometry(QtCore.QRect(200, 210, 60, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.select_video.setFont(font)
        self.select_video.setObjectName("select_video")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(40, 270, 51, 30))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.collect_page = QtWidgets.QComboBox(Dialog)
        self.collect_page.setGeometry(QtCore.QRect(120, 270, 71, 25))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        self.collect_page.setFont(font)
        self.collect_page.setObjectName("collect_page")
        self.collect_page.addItem("")
        self.collect_page.addItem("")
        self.collect_page.addItem("")
        self.line_3 = QtWidgets.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(0, 60, 1301, 21))
        self.line_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.line_3.setLineWidth(1)
        self.line_3.setMidLineWidth(1)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setObjectName("line_3")
        self.line.raise_()
        self.collect_state.raise_()
        self.collect_data.raise_()
        self.collect_start.raise_()
        self.progressBar.raise_()
        self.label_9.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.line_2.raise_()
        self.main_win.raise_()
        self.collect_user.raise_()
        self.collect_password.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.collect_keyword.raise_()
        self.label_4.raise_()
        self.select_pic.raise_()
        self.select_video.raise_()
        self.label_5.raise_()
        self.collect_page.raise_()
        self.line_3.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "微博爬虫软件"))
        self.collect_start.setText(_translate("Dialog", "开始采集"))
        self.label_9.setText(_translate("Dialog", "进度"))
        self.label_10.setText(_translate("Dialog", "状态"))
        self.label_11.setText(_translate("Dialog", "微博内容"))
        self.label.setText(_translate("Dialog", "微博密码"))
        self.label_2.setText(_translate("Dialog", "微博账号"))
        self.label_3.setText(_translate("Dialog", "采集内容"))
        self.label_4.setText(_translate("Dialog", "采集选项"))
        self.select_pic.setText(_translate("Dialog", "图片"))
        self.select_video.setText(_translate("Dialog", "视频"))
        self.label_5.setText(_translate("Dialog", "采集页数"))
        self.collect_page.setItemText(0, _translate("Dialog", "前10页"))
        self.collect_page.setItemText(1, _translate("Dialog", "前20页"))
        self.collect_page.setItemText(2, _translate("Dialog", "前50页"))

