apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    name: frontend
spec:
  type: NodePort
  ports:
    #the port that this service should serve on
    - port: 80
    selector:
      name: frontend